# Blueprint do Render
# Cria automaticamente o frontend e a API

services:

  # =====================================================
  # FRONTEND ANGULAR
  # =====================================================

  - type: web
    name: stake-web
    runtime: static

    rootDir: web

    buildCommand: npm install && npm run build

    staticPublishPath: dist/stake-ui/browser

    envVars:
      - key: API_URL
        sync: false

    routes:
      - type: rewrite
        source: /*
        destination: /index.html


  # =====================================================
  # BACKEND ASP.NET CORE
  # =====================================================

  - type: web
    name: stake-api

    runtime: docker

    plan: free

    rootDir: api/StakeApi

    dockerfilePath: ./Dockerfile

    envVars:

      - key: ConnectionStrings__DefaultConnection
        sync: false

      - key: AllowedOrigins__0
        sync: false

      - key: Auth__Password
        sync: false

      - key: Auth__JwtSecret
        sync: false
